In [19]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression

In [28]:
df = np.round(pd.read_csv("50_Startups.csv")[['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

,R&D Spend,Administration,Marketing Spend,Profit
21,8.0,15.0,30.0,11.0
37,4.0,5.0,20.0,9.0
2,15.0,10.0,41.0,19.0
14,12.0,16.0,26.0,13.0
44,2.0,15.0,3.0,7.0


In [29]:
df = df.iloc[:,0:-1]
df

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.0
37,4.0,5.0,20.0
2,15.0,10.0,41.0
14,12.0,16.0,26.0
44,2.0,15.0,3.0


In [30]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

C:\Users\abdee\AppData\Local\Temp\ipykernel_26904\766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\abdee\AppData\Local\Temp\ipykernel_26904\766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\abdee\AppData\Local\Temp\ipykernel_26904\766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan


In [31]:
df.head()

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.0
37,NaN,5.0,20.0
2,15.0,10.0,41.0
14,12.0,NaN,26.0
44,2.0,15.0,NaN


In [32]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [33]:
df0

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,9.25,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.25,26.00
44,2.00,15.00,29.25


In [34]:
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
21,8.0,15.00,30.00
37,NaN,5.00,20.00
2,15.0,10.00,41.00
14,12.0,11.25,26.00
44,2.0,15.00,29.25


In [35]:
X = df1.iloc[[0,2,3,4,],1:3]
X

,Administration,Marketing Spend
21,15.00,30.00
2,10.00,41.00
14,11.25,26.00
44,15.00,29.25


In [36]:
y = df1.iloc[[0,2,3,4,],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [38]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df.iloc[1,1:].values.reshape(1,2))

C:\Users\abdee\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.14158651])

In [41]:
df1.iloc[1,0] = 23.14
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.14,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.25,26.00
44,2.00,15.00,29.25


In [44]:
df1.iloc[3,1] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.0,30.00
37,23.14,5.0,20.00
2,15.00,10.0,41.00
14,12.00,NaN,26.00
44,2.00,15.0,29.25


In [45]:
X = df1.iloc[[0,2,3,4,],[0,2]]
X

,R&D Spend,Marketing Spend
21,8.0,30.00
2,15.0,41.00
14,12.0,26.00
44,2.0,29.25


In [46]:
y = df1.iloc[[0,1,2,4,],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [47]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\abdee\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.99236091])

In [50]:
df1.iloc[3,1] = 10.99
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.14,5.00,20.00
2,15.00,10.00,41.00
14,12.00,10.99,26.00
44,2.00,15.00,29.25


In [51]:
df1.iloc[4,-1] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.0
37,23.14,5.00,20.0
2,15.00,10.00,41.0
14,12.00,10.99,26.0
44,2.00,15.00,NaN


In [52]:
X = df1.iloc[0:4, 0:2]
X

,R&D Spend,Administration
21,8.00,15.00
37,23.14,5.00
2,15.00,10.00
14,12.00,10.99


In [53]:
y = df.iloc[0:4, -1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [55]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4, 0:2].values.reshape(1,2))

C:\Users\abdee\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([31.20151456])

In [57]:
df1.iloc[4,-1] = 31.20
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.0
37,23.14,5.00,20.0
2,15.00,10.00,41.0
14,12.00,10.99,26.0
44,2.00,15.00,31.2


In [58]:
df1 - df0

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,13.89,0.00,0.00
2,0.00,0.00,0.00
14,0.00,-0.26,0.00
44,0.00,0.00,1.95


In [63]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

,R&D Spend,Administration,Marketing Spend
21,8.0,15.00,30.0
37,NaN,5.00,20.0
2,15.0,10.00,41.0
14,12.0,10.99,26.0
44,2.0,15.00,31.2


In [64]:

X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

C:\Users\abdee\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.23479078])

In [65]:
df2.iloc[1,0] = 23.78

In [67]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\abdee\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.21271272])

In [68]:
df2.iloc[3,1] = 11.22

In [69]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

C:\Users\abdee\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([38.87979054])

In [70]:
df2.iloc[4,-1] = 31.56
df2

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.78,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.22,26.00
44,2.00,15.00,31.56


In [71]:
df2 - df1

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,0.64,0.00,0.00
2,0.00,0.00,0.00
14,0.00,0.23,0.00
44,0.00,0.00,0.36


In [73]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3


,R&D Spend,Administration,Marketing Spend
21,8.0,15.00,30.00
37,NaN,5.00,20.00
2,15.0,10.00,41.00
14,12.0,11.22,26.00
44,2.0,15.00,31.56


In [74]:
#ab too dekh lena thik 
#29-7-2026

In [60]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# 1. Original DataFrame jisme missing values hain
df_orig = df.copy()

# Sabhi columns ke missing indices ko track karna
nan_indices = {col: df_orig[df_orig[col].isna()].index for col in df_orig.columns}

# Step 0: Mean Imputation (0th Iteration)
df_curr = df_orig.copy()
for col in df_curr.columns:
    df_curr[col] = df_curr[col].fillna(df_curr[col].mean())

# Iterations run karne ka loop
max_iter = 20

for iteration in range(1, max_iter + 1):
    df_prev = df_curr.copy()
    
    # Har feature/column ke upar loop
    for col in df_curr.columns:
        # Agar iss column me originally missing values the
        if len(nan_indices[col]) > 0:
            
            # Missing row positions ko firse NaN karo
            df_curr.loc[nan_indices[col], col] = np.nan
            
            # Non-missing rows ko training ke liye aur missing rows ko prediction ke liye split karo
            train_mask = df_curr[col].notna()
            
            X_train = df_curr.loc[train_mask, [c for c in df_curr.columns if c != col]]
            y_train = df_curr.loc[train_mask, col]
            
            X_pred = df_curr.loc[~train_mask, [c for c in df_curr.columns if c != col]]
            
            # Linear Regression Model Fit karke missing values predict karo
            lr = LinearRegression()
            lr.fit(X_train, y_train)
            df_curr.loc[~train_mask, col] = lr.predict(X_pred)
            
    # Difference check karo (Convergence verify karne ke liye)
    print(f"\n--- Iteration {iteration} Difference (df_curr - df_prev) ---")
    print(df_curr - df_prev)

# Final Imputed DataFrame
print("\nFinal Imputed DataFrame:")
print(df_curr)


--- Iteration 1 Difference (df_curr - df_prev) ---
    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000              0.0
37  15.256819        0.000000              0.0
2    0.000000        0.000000              0.0
14   0.000000        0.101816              0.0
44   0.000000        0.000000              0.0

--- Iteration 2 Difference (df_curr - df_prev) ---
    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000              0.0
37   0.530237        0.000000              0.0
2    0.000000        0.000000              0.0
14   0.000000        0.097901              0.0
44   0.000000        0.000000              0.0

--- Iteration 3 Difference (df_curr - df_prev) ---
    R&D Spend  Administration  Marketing Spend
21     0.0000        0.000000              0.0
37     0.5283        0.000000              0.0
2      0.0000        0.000000              0.0
14     0.0000        0.094669              0.0
44     0.0000        0.000000              0.